namespace BigDataAcademy.Model.Claim;

public partial class ClaimFaker<TClaim>
{
    private static readonly string[] ProductLines =
    {
        "Commercial Auto Line", "Personal Auto Line", "Property", "Road Risks",
    };

    private static readonly string[] States =
    {
        "open", "closed",
    };

    private static readonly string[] Brokerages =
    {
        "Britannia Brokers",
        "Union Street Securities",
        "Thames Valley Investments",
        "London Bridge Capital",
        "Westminster Wealth Management",
        "Oxfordshire Brokers",
        "Yorkshire Financial Group",
        "Windsor Securities",
        "Bristol Capital Advisors",
        "Manchester Money Managers",
        "Liverpool Investment Services",
        "Birmingham Broking Solutions",
        "Nottinghamshire Wealth",
        "Newcastle Securities",
        "Edinburgh Equity Partners",
        "Glasgow Gate Capital",
        "Cardiff Investment Group",
        "Belfast Brokers",
        "Southampton Securities",
        "Leeds Asset Management",
        "Cambridge Capital Advisors",
        "Essex Wealth Management",
        "Surrey Securities",
        "Sussex Stockbrokers",
        "Norfolk Investment Solutions",
        "Kent Financial Group",
        "Glasgow Glen Securities",
        "Aberdeen Asset Managers",
        "Dundee Investment Services",
        "Edinburgh Equity Exchange",
        "Cardiff Capital Brokers",
        "Belfast Bond Traders",
        "Manchester Money Market",
        "Birmingham Bridge Capital",
        "Nottinghamshire Investment Bank",
        "Oxfordshire Options",
        "Liverpool Lenders",
        "Leeds Leveraged Finance",
        "Bristol Bond Brokers",
        "Newcastle National Securities",
        "Edinburgh Elite Equity",
        "Glasgow Global Investments",
        "Cardiff Corporate Finance",
        "Belfast Bridge Street Brokers",
        "Southampton Stock Exchange",
        "Surrey Structured Securities",
        "Kent Key Investments",
        "Cambridge Currency Traders",
        "Aberdeen Advisory Services",
        "Dundee Derivatives Market",
        "Edinburgh Eurozone Brokers",
        "Glasgow Growth Fund",
        "Cardiff Capital Market Solutions",
        "Belfast Business Brokers",
        "Manchester Money Managers",
        "Birmingham Bond Traders",
        "Nottinghamshire Investment Advisors",
        "Oxfordshire Options Trading",
        "Liverpool Leveraged Finance",
        "Leeds Loan Brokers",
        "Bristol Bankers",
        "Newcastle National Wealth",
        "Edinburgh Emerging Markets",
        "Glasgow Gatekeepers",
        "Cardiff Capital Consultants",
        "Belfast Bond Brokers",
        "Southampton Securities",
        "Surrey Sustainable Investments",
        "Kent Key Capital",
        "Cambridge Corporate Finance",
        "Aberdeen Asset Management",
        "Dundee Derivatives Exchange",
        "Edinburgh Earnings Advisors",
        "Glasgow Growth Securities",
        "Cardiff Capital Trust",
        "Belfast Business Partners",
        "Manchester Money Exchange",
        "Birmingham Bond Market",
        "Nottinghamshire Investment Solutions",
        "Oxfordshire Options Advisors",
        "Liverpool Loan Traders",
        "Leeds Lending Services",
        "Bristol Bankers",
        "Newcastle National Bank",
        "Edinburgh Equity Exchange",
        "Glasgow Gate Securities",
        "Cardiff Capital Markets",
        "Belfast Bond Advisory",
        "Southampton Stockbrokers",
        "Surrey Structured Finance",
        "Kent Key Investments",
        "Cambridge Capital Solutions",
        "Aberdeen Advisory Group",
        "Dundee Derivatives Brokers",
        "Edinburgh Emerging Wealth",
        "Glasgow Gatekeepers",
        "Cardiff Capital Consultants",
        "Belfast Business Finance",
        "Manchester Money Lenders",
        "Birmingham Bond Advisors",
    };

    private static readonly string[] ClaimTiers =
    {
        "low", "medium", "high",
    };

    private static readonly string[] Currencies =
    {
        "EUR", "GBP",
    };

    private static readonly string[] FaultRatings =
    {
        "fault", "non-fault", "not applicable", "unknown",
    };

    private static readonly string[] HowReported =
    {
        "phone", "web", "web", "mail", "other",
    };

    private static readonly string[] LossCauses =
    {
        "I accidentally mistook my car for a piñata and swung at it during a birthday party.",
        "I tried to impress my date by juggling flaming torches and accidentally set fire to my living room.",
        "I attempted a DIY home renovation project and ended up with a sink in my ceiling.",
        "My pet parrot developed a sudden liking for expensive designer shoes and chewed through my entire collection.",
        "I decided to test the durability of my smartphone by dropping it from a hot air balloon. It didn't survive the fall.",
        "I tried to recreate a famous movie scene by driving my car through a billboard. The billboard won.",
        "I accidentally used superglue instead of eye drops and spent the entire day with my eyelids glued shut.",
        "During a yoga session, I attempted a complicated pose and accidentally knocked over an expensive vase.",
        "I left a bag of marshmallows in my car on a hot summer day and came back to find a melted marshmallow mess.",
        "I mistook my new laptop for a cutting board and accidentally sliced it with a kitchen knife.",
        "While trying to impress my friends with my golf skills, I hit a hole-in-one directly into a neighbor's window.",
        "I tried to make homemade fireworks for a celebration but ended up setting off my neighbor's sprinkler system instead.",
        "I attempted to make a grand entrance at a party by sliding down a staircase banister and ended up crashing through a glass coffee table.",
        "I decided to test the bounce of a new basketball by throwing it off the roof, only to have it land in my neighbor's swimming pool.",
        "While attempting to take a selfie with a wild squirrel, it mistook my phone for food and ran off with it.",
        "I thought it would be fun to try rollerblading down a steep hill, but I quickly lost control and crashed into a parked ice cream truck.",
        "I attempted to fix a leaky faucet with duct tape, but the pressure built up and caused a small water explosion in my bathroom.",
        "During a backyard barbecue, I accidentally launched a flaming marshmallow into a neighbor's garden, setting their flowers ablaze.",
        "I borrowed my friend's drone to capture a stunning aerial video, but it ended up crashing into a tree and getting entangled in a squirrel's nest.",
        "While trying to impress my friends with my dance moves, I slipped on a banana peel and crashed into a wedding cake.",
        "I accidentally mistook a can of spray paint for deodorant and ended up with purple armpits for a week.",
        "I attempted to ride a unicycle down a flight of stairs, but gravity had other plans.",
        "While attempting to do a backflip on a trampoline, I overshot and landed in the neighbor's swimming pool.",
        "I thought it would be fun to use my leaf blower to simulate a tornado, but it ended up blowing away my neighbor's laundry.",
        "I decided to test the buoyancy of a helium balloon by tying it to my cat's collar - the cat was not amused.",
        "I tried to capture a squirrel that was stealing birdseed by setting up a complex Rube Goldberg machine, but it backfired and launched birdseed all over my living room.",
        "I attempted to create a homemade water slide in my backyard using a tarp and dish soap, but it turned into a muddy disaster.",
        "I thought it would be hilarious to surprise my friends with a confetti cannon, but I accidentally set it off indoors, covering everything in a colorful mess.",
        "I decided to try out a unicycle for the first time and promptly crashed into a signpost, knocking it over.",
        "I tried to impress my friends by attempting a high jump over a fence, but I got stuck on top and had to be rescued by a passerby.",
        "I thought it would be fun to host a water balloon fight indoors, forgetting that I had expensive electronics lying around.",
        "I decided to test the fire alarm system in my apartment by lighting a candle directly under the smoke detector, triggering a false alarm.",
        "While playing a game of Frisbee, I accidentally threw it onto the roof and attempted to retrieve it by climbing up a tree, only to get stuck.",
        "I attempted to build a makeshift ramp for my bike using a plank of wood, but it broke upon impact, sending me flying into a bush.",
        "I thought it would be fun to have a contest to see who could hold their breath the longest underwater in the bathtub, but we forgot to account for the overflowing water.",
        "I decided to test the aerodynamics of a model airplane by launching it from my apartment balcony, but it got caught in a gust of wind and flew into a neighbor's open window.",
        "While attempting to perform a magic trick, I accidentally made my friend's watch disappear and couldn't figure out how to bring it back.",
        "I thought it would be entertaining to try a new hair dye color at home, but I accidentally dyed my hair a bright shade of neon green.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to ride a scooter downhill, the handlebar detached, causing me to lose control and crash into a pile of leaves.",
        "I thought it would be funny to try tightrope walking between two trees in the park, but I ended up slipping and falling into a pond.",
        "I decided to test the limits of a bungee cord by attaching it to my shopping cart and attempting to bungee jump off a bridge, resulting in a torn cart and a very confused cashier.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be amusing to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of a new pair of shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to try water skiing in a small inflatable pool, but I ended up flipping over and getting stuck with my feet in the air.",
        "I decided to test the strength of my car's bumper by nudging a shopping cart with it, but the cart ended up rolling downhill and crashing into a parked car.",
        "While attempting to parallel park, I accidentally hit the gas instead of the brake and ended up parking halfway on the sidewalk.",
        "I thought it would be entertaining to have a trampoline party in my living room, but it quickly turned into a disaster with the trampoline crashing through the floor.",
        "I decided to test the non-stick capabilities of a frying pan by cooking an omelet without any oil, resulting in a burnt mess that wouldn't come off.",
        "While trying to perform a magic trick with cards, I accidentally threw the entire deck out the window.",
        "I thought it would be funny to challenge my friends to a race in a supermarket using shopping carts, but we ended up crashing into a display of canned soup.",
        "I decided to test the durability of a bicycle helmet by hitting it with a hammer, only to have the hammer bounce back and hit me on the head.",
        "While attempting to make a grand entrance at a costume party, my cape got caught on a doorknob and I tripped, crashing into the cake.",
        "I thought it would be fun to have a game of indoor mini-golf, but I accidentally hit the ball into a valuable antique vase.",
        "I decided to test the sharpness of a kitchen knife by attempting to slice a watermelon held in my hand, resulting in a trip to the emergency room.",
        "While trying to capture the perfect selfie with a seagull at the beach, it swooped down and stole my phone.",
        "I thought it would be entertaining to try tightrope walking across a narrow fence, but I ended up falling into a pond.",
        "I decided to test the water resistance of my watch by wearing it in the shower, forgetting that it was not waterproof.",
        "While attempting a DIY haircut, I accidentally used the wrong attachment on the trimmer and ended up with a bald patch.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by attempting to repair my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the speed of a ceiling fan by tossing a feather into the air, resulting in a feather explosion throughout the room.",
        "While attempting to play fetch with my dog in the living room, I accidentally knocked over a lamp with the toy.",
        "I thought it would be fun to use a fire extinguisher as a makeshift rocket launcher, but it only resulted in a cloud of white foam and a ruined carpet.",
        "I decided to test the flexibility of my yoga skills by attempting a full split, but I ended up pulling a muscle and toppling over.",
        "While trying to make a grand entrance at a party, I tripped on the red carpet and knocked over the buffet table.",
        "I thought it would be funny to surprise my roommate by hiding in a large box, but they mistook it for garbage and threw it out.",
        "I decided to test the sharpness of a kitchen knife by attempting to slice a tomato held in my hand, resulting in a small but messy injury.",
        "While attempting to jump over a puddle in stylish boots, I landed in the puddle and got stuck, requiring assistance to free myself.",
        "I thought it would be entertaining to have a friendly wrestling match with a life-size cardboard cutout, but it ended with me being pinned to the ground.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the limits of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
        "I thought it would be funny to dress up as a scarecrow and surprise my friends in the garden, but I ended up scaring away the birds and ruining the plants.",
        "I decided to test the strength of a hammock by jumping onto it from a tree branch, only to have it rip and send me crashing to the ground.",
        "While attempting to perform a magic trick with fire, I accidentally set my curtains ablaze.",
        "I thought it would be entertaining to try juggling eggs, but they slipped out of my hands and made a mess all over the kitchen floor.",
        "I decided to test the endurance of my running shoes by participating in a marathon, but they fell apart halfway through the race.",
        "While trying to impress my friends with my acrobatic skills, I attempted a backflip and crashed into a table full of snacks.",
        "I thought it would be fun to build a homemade water slide in the backyard, but it turned into a muddy disaster after the first slide.",
        "I decided to test the durability of my phone by tossing it in the air and attempting to catch it, but I missed and it landed in a puddle.",
        "While attempting to balance on a soccer ball, I lost my footing and crashed into a stack of pizza boxes.",
        "I thought it would be funny to try skateboarding down a steep hill, but I quickly lost control and crashed into a mailbox.",
        "I decided to test the strength of a tree branch by hanging a tire swing on it, but the branch snapped, and I fell to the ground.",
        "While trying to demonstrate a karate move, I accidentally kicked a hole in the wall.",
        "I thought it would be entertaining to have a pillow fight in the living room, but we accidentally knocked over a vase and shattered it.",
        "I decided to test the slipperiness of a banana peel by stepping on it, but it sent me sliding across the floor and crashing into a bookshelf.",
        "While attempting to climb a tree to rescue a stranded cat, I got stuck and had to be rescued myself.",
        "I thought it would be fun to try tightrope walking between two trees, but I ended up falling and getting tangled in a clothesline.",
        "I decided to test the strength of a piñata by using a baseball bat, but I swung too hard and accidentally hit my neighbor's car.",
        "While trying to balance on a tightrope, I lost my footing and crashed into a picnic table full of food.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a swing, but I ended up face-planting into the ground.",
        "I decided to test the stability of a ladder by standing on the very top, but it wobbled and I fell off.",
        "While attempting to do a handstand on a yoga ball, I lost my balance and crashed into a set of dumbbells.",
        "I thought it would be entertaining to have a water gun fight in the living room, but we ended up soaking all the furniture.",
        "I decided to test the durability of a watermelon by dropping it from a balcony, but it shattered upon impact and made a mess on the sidewalk.",
        "While trying to take a selfie with a dolphin at the aquarium, my phone slipped out of my hand and fell into the dolphin tank.",
        "I thought it would be fun to use roller skates instead of shoes for a day, but I ended up falling down the stairs.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be funny to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of my new shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by repairing my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the endurance of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
        "I thought it would be funny to dress up as a scarecrow and surprise my friends in the garden, but I ended up scaring away the birds and ruining the plants.",
        "I decided to test the strength of a hammock by jumping onto it from a tree branch, only to have it rip and send me crashing to the ground.",
        "While attempting to perform a magic trick with fire, I accidentally set my curtains ablaze.",
        "I thought it would be entertaining to try juggling eggs, but they slipped out of my hands and made a mess all over the kitchen floor.",
        "I decided to test the durability of my running shoes by participating in a marathon, but they fell apart halfway through the race.",
        "While trying to impress my friends with my acrobatic skills, I attempted a backflip and crashed into a table full of snacks.",
        "I thought it would be fun to build a homemade water slide in the backyard, but it turned into a muddy disaster after the first slide.",
        "I decided to test the slipperiness of a banana peel by stepping on it, but it sent me sliding across the floor and crashing into a bookshelf.",
        "While attempting to climb a tree to rescue a stranded cat, I got stuck and had to be rescued myself.",
        "I thought it would be fun to try tightrope walking between two trees, but I ended up falling and getting tangled in a clothesline.",
        "I decided to test the strength of a piñata by using a baseball bat, but I swung too hard and accidentally hit my neighbor's car.",
        "While trying to balance on a tightrope, I lost my footing and crashed into a picnic table full of food.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a swing, but I ended up face-planting into the ground.",
        "I decided to test the stability of a ladder by standing on the very top, but it wobbled and I fell off.",
        "While attempting to do a handstand on a yoga ball, I lost my balance and crashed into a set of dumbbells.",
        "I thought it would be entertaining to have a water gun fight in the living room, but we ended up soaking all the furniture.",
        "I decided to test the durability of a watermelon by dropping it from a balcony, but it shattered upon impact and made a mess on the sidewalk.",
        "While trying to take a selfie with a dolphin at the aquarium, my phone slipped out of my hand and fell into the dolphin tank.",
        "I thought it would be fun to use roller skates instead of shoes for a day, but I ended up falling down the stairs.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be funny to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of my new shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by repairing my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the endurance of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
        "I thought it would be funny to dress up as a scarecrow and surprise my friends in the garden, but I ended up scaring away the birds and ruining the plants.",
        "I decided to test the strength of a hammock by jumping onto it from a tree branch, only to have it rip and send me crashing to the ground.",
        "While attempting to perform a magic trick with fire, I accidentally set my curtains ablaze.",
        "I thought it would be entertaining to try juggling eggs, but they slipped out of my hands and made a mess all over the kitchen floor.",
        "I decided to test the durability of my running shoes by participating in a marathon, but they fell apart halfway through the race.",
        "While trying to impress my friends with my acrobatic skills, I attempted a backflip and crashed into a table full of snacks.",
        "I thought it would be fun to build a homemade water slide in the backyard, but it turned into a muddy disaster after the first slide.",
        "I decided to test the slipperiness of a banana peel by stepping on it, but it sent me sliding across the floor and crashing into a bookshelf.",
        "While attempting to climb a tree to rescue a stranded cat, I got stuck and had to be rescued myself.",
        "I thought it would be fun to try tightrope walking between two trees, but I ended up falling and getting tangled in a clothesline.",
        "I decided to test the strength of a piñata by using a baseball bat, but I swung too hard and accidentally hit my neighbor's car.",
        "While trying to balance on a tightrope, I lost my footing and crashed into a picnic table full of food.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a swing, but I ended up face-planting into the ground.",
        "I decided to test the stability of a ladder by standing on the very top, but it wobbled and I fell off.",
        "While attempting to do a handstand on a yoga ball, I lost my balance and crashed into a set of dumbbells.",
        "I thought it would be entertaining to have a water gun fight in the living room, but we ended up soaking all the furniture.",
        "I decided to test the durability of a watermelon by dropping it from a balcony, but it shattered upon impact and made a mess on the sidewalk.",
        "While trying to take a selfie with a dolphin at the aquarium, my phone slipped out of my hand and fell into the dolphin tank.",
        "I thought it would be fun to use roller skates instead of shoes for a day, but I ended up falling down the stairs.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be funny to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of my new shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by repairing my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the endurance of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
        "I thought it would be funny to dress up as a scarecrow and surprise my friends in the garden, but I ended up scaring away the birds and ruining the plants.",
        "I decided to test the strength of a hammock by jumping onto it from a tree branch, only to have it rip and send me crashing to the ground.",
        "While attempting to perform a magic trick with fire, I accidentally set my curtains ablaze.",
        "I thought it would be entertaining to try juggling eggs, but they slipped out of my hands and made a mess all over the kitchen floor.",
        "I decided to test the durability of my running shoes by participating in a marathon, but they fell apart halfway through the race.",
        "While trying to impress my friends with my acrobatic skills, I attempted a backflip and crashed into a table full of snacks.",
        "I thought it would be fun to build a homemade water slide in the backyard, but it turned into a muddy disaster after the first slide.",
        "I decided to test the slipperiness of a banana peel by stepping on it, but it sent me sliding across the floor and crashing into a bookshelf.",
        "While attempting to climb a tree to rescue a stranded cat, I got stuck and had to be rescued myself.",
        "I thought it would be fun to try tightrope walking between two trees, but I ended up falling and getting tangled in a clothesline.",
        "I decided to test the strength of a piñata by using a baseball bat, but I swung too hard and accidentally hit my neighbor's car.",
        "While trying to balance on a tightrope, I lost my footing and crashed into a picnic table full of food.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a swing, but I ended up face-planting into the ground.",
        "I decided to test the stability of a ladder by standing on the very top, but it wobbled and I fell off.",
        "While attempting to do a handstand on a yoga ball, I lost my balance and crashed into a set of dumbbells.",
        "I thought it would be entertaining to have a water gun fight in the living room, but we ended up soaking all the furniture.",
        "I decided to test the durability of a watermelon by dropping it from a balcony, but it shattered upon impact and made a mess on the sidewalk.",
        "While trying to take a selfie with a dolphin at the aquarium, my phone slipped out of my hand and fell into the dolphin tank.",
        "I thought it would be fun to use roller skates instead of shoes for a day, but I ended up falling down the stairs.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be funny to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of my new shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by repairing my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the endurance of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
        "I thought it would be funny to dress up as a scarecrow and surprise my friends in the garden, but I ended up scaring away the birds and ruining the plants.",
        "I decided to test the strength of a hammock by jumping onto it from a tree branch, only to have it rip and send me crashing to the ground.",
        "While attempting to perform a magic trick with fire, I accidentally set my curtains ablaze.",
        "I thought it would be entertaining to try juggling eggs, but they slipped out of my hands and made a mess all over the kitchen floor.",
        "I decided to test the durability of my running shoes by participating in a marathon, but they fell apart halfway through the race.",
        "While trying to impress my friends with my acrobatic skills, I attempted a backflip and crashed into a table full of snacks.",
        "I thought it would be fun to build a homemade water slide in the backyard, but it turned into a muddy disaster after the first slide.",
        "I decided to test the slipperiness of a banana peel by stepping on it, but it sent me sliding across the floor and crashing into a bookshelf.",
        "While attempting to climb a tree to rescue a stranded cat, I got stuck and had to be rescued myself.",
        "I thought it would be fun to try tightrope walking between two trees, but I ended up falling and getting tangled in a clothesline.",
        "I decided to test the strength of a piñata by using a baseball bat, but I swung too hard and accidentally hit my neighbor's car.",
        "While trying to balance on a tightrope, I lost my footing and crashed into a picnic table full of food.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a swing, but I ended up face-planting into the ground.",
        "I decided to test the stability of a ladder by standing on the very top, but it wobbled and I fell off.",
        "While attempting to do a handstand on a yoga ball, I lost my balance and crashed into a set of dumbbells.",
        "I thought it would be entertaining to have a water gun fight in the living room, but we ended up soaking all the furniture.",
        "I decided to test the durability of a watermelon by dropping it from a balcony, but it shattered upon impact and made a mess on the sidewalk.",
        "While trying to take a selfie with a dolphin at the aquarium, my phone slipped out of my hand and fell into the dolphin tank.",
        "I thought it would be fun to use roller skates instead of shoes for a day, but I ended up falling down the stairs.",
        "I decided to test the strength of a chair by standing on it, but it collapsed, and I fell onto the floor.",
        "While attempting to fix a leaky roof, I accidentally stepped on a weak spot and fell through the ceiling, landing in the living room.",
        "I thought it would be funny to try riding a unicycle while juggling knives, but it quickly turned into a chaotic scene with knives flying in all directions.",
        "I decided to test the durability of my new shoes by wearing them during a muddy obstacle course race, only to have them completely ruined by the end.",
        "While attempting to breakdance on a slippery dance floor, I ended up doing the splits and tearing my pants.",
        "I thought it would be fun to ride a shopping cart down a steep hill, but it quickly got out of control and crashed into a parked car.",
        "I decided to test the stickiness of super glue by repairing my broken glasses, only to glue them to my forehead.",
        "While trying to show off my basketball skills, I attempted a slam dunk and shattered the backboard.",
        "I thought it would be funny to dress up as a superhero and attempt to fly off a low roof, but I ended up crash-landing into a bush.",
        "I decided to test the flotation capabilities of my inflatable pool toys by using them in a regular swimming pool, only to discover they were not designed for it and promptly deflated.",
        "While attempting to capture a spider in my house, I accidentally knocked over a shelf, causing a chain reaction that toppled multiple shelves.",
        "I thought it would be fun to use a leaf blower to dry my wet laundry, but it ended up scattering clothes all over the neighborhood.",
        "I decided to test the strength of a ladder by standing on the very top rung, resulting in a toppled ladder and a bruised ego.",
        "While trying to impress my friends with my dance moves, I tripped on my shoelaces and fell into a cake.",
        "I thought it would be entertaining to have a water balloon fight in the living room, but we ended up causing a small flood.",
        "I decided to test the endurance of my trampoline by attempting a double backflip, but I overshot and landed in a tree.",
        "While attempting to fix a leaky faucet, I accidentally broke the handle and water started spraying everywhere.",
        "I thought it would be fun to try riding a skateboard down a staircase, but I lost my balance and crashed into a wall.",
        "I decided to test the heat resistance of my hairdryer by pointing it at a lit candle, resulting in a singed hairstyle and a burnt hairdryer.",
        "While trying to take a selfie with a statue, I accidentally knocked it over and broke it into pieces.",
    };

    private static readonly string?[] LossTypes =
    {
        "motor", "property", null,
    };

    private static readonly string[] Situations =
    {
        "ENG",
        "SCO",
        "WAL",
        "NIR",
    };
}
