trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/*
    exclude:
      - src/BigDataAcademy.Api/*
      - src/BigDataAcademy.Generator/*
      - src/big-data-academy-api.Dockerfile

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'mkilinski/big-data-academy-oauth'
        dockerfile: 'src/big-data-academy-oauth.Dockerfile'
        containerRegistry: 'michalbda'
        tags: |
          $(Build.BuildId)
          latest
