namespace BigDataAcademy.Model.Motor;

public partial class MotorFaker<TMotor>
{
    private static readonly string[] TotalLossDecisions =
    {
        "Repair", "TotalLoss", "TotalLoss/Repair",
    };

    private static readonly string[] DamageDescriptions =
    {
        "After a heated dance-off with a rogue shopping cart, the fender decided to take an early retirement.",
        "Due to an unexpected encounter with a low-flying UFO, the roof now doubles as a landing pad for extraterrestrials.",
        "The side mirror, feeling adventurous, decided to run off with a passing circus troupe, leaving the car's ego bruised.",
        "In a valiant attempt to mimic a superhero landing, the bumper discovered it lacked the necessary powers and crumbled under the pressure.",
        "During a high-speed race with a squirrel, the windshield lost by a nut's length.",
        "The car's tire, channeling its inner Houdini, decided to disappear without a trace, leaving the rest of the vehicle deflated.",
        "The doors, after a brief rebellion, have taken up acting and are now auditioning for 'Escape from the Garage: The Sequel.'",
        "The hood ornament decided it was time to explore the world beyond cars and hitchhiked a ride with a migrating bird.",
        "A band of mischievous monkeys mistook the antenna for a tree branch, resulting in an impromptu monkey bar session that left it bent out of shape.",
        "In an attempt to embrace its inner Transformer, the car developed a talent for converting into a pile of mismatched puzzle pieces.",
        "The rearview mirror, overwhelmed by its own reflection, decided to call it quits and pursue a career in existential philosophy.",
        "After a thrilling mud-wrestling match with a particularly aggressive puddle, the car's paint job now boasts a fashionable speckled pattern.",
        "The engine, tired of a sedentary lifestyle, went on strike and demanded to be traded in for a brand-new espresso machine.",
        "In a stunning display of aerodynamics, the hubcap managed to take flight and become the neighborhood's newest Frisbee champion.",
        "The sunroof, eager to join the circus, practiced its acrobatics and executed a perfect vanishing act.",
        "The steering wheel, feeling underappreciated, rolled off in search of a more hands-on relationship.",
        "During a car wash, the soap dispenser took its role a bit too seriously and unleashed a foam party that short-circuited the radio.",
        "The gas cap, inspired by fashion week, decided to become the car's trendiest earring but unfortunately got left behind at the pump.",
        "In an attempt to prove it could fly, the spare tire soared through the air but crash-landed in a parallel parking disaster.",
        "The dashboard, tired of monotony, decided to spice things up by transforming into a disco ball and throwing a rave party.",
        "The seat covers, seeking a more glamorous life, ran away to join the cast of 'Fast and Furious: Upholstery Drift.'",
        "The cup holder, in an act of rebellion, launched an all-out protest against lukewarm beverages and demanded only the hottest coffee on the road.",
        "The rear bumper, after a heated argument with a parking sign, decided to ghost the car, leaving it rear-endless.",
        "The air conditioning, embracing its inner polar bear, decided to throw an Arctic blast party that left the passengers frozen with excitement.",
        "The glove compartment, always a fan of magic tricks, disappeared into thin air along with the owner's favorite pair of gloves.",
        "The CD player, in an attempt to upgrade to the digital age, spontaneously combusted in a musical explosion of outdated hits.",
        "The windshield wipers, aspiring conductors, attempted to lead a symphony of raindrops but ended up tangled in a cacophony of confusion.",
        "The exhaust pipe, feeling rebellious, tried to break free and become a trumpet player in a jazz band but blew its own gasket instead.",
        "The rear seat belts, tired of playing second fiddle, formed a rebellion and demanded a front-row seat in the car's safety hierarchy.",
        "The rearview mirror, in a desperate plea for attention, resorted to moonlighting as a disco ball but was promptly rejected by the dance floor.",
        "The trunk, aspiring to be a magician's assistant, attempted the 'disappearing act' trick but accidentally transported itself to a parallel universe.",
        "The windshield, after being hit by a mysterious floating meatball, now bears the saucy marks of an extraterrestrial pasta invasion.",
        "The cup holders, fueled by the desire to become Olympic athletes, engaged in a fierce competition that ended with shattered dreams and spilled drinks.",
        "The front bumper, in an attempt to become a rock star, belted out a powerful rendition of 'Highway to Destruction' and shattered the car's dreams of safety.",
        "The side view mirror, embracing its artistic side, decided to explore the world of abstract expressionism and created a unique cracked glass masterpiece.",
        "The radio, tired of hearing the same old tunes, spontaneously transformed into a karaoke machine and serenaded the car with an off-key rendition of 'Bohemian Rhapsody.'",
        "The antenna, dreaming of being an intergalactic communicator, attempted to transmit signals to extraterrestrial life forms but ended up causing a neighborhood-wide TV blackout instead.",
        "The side door, harboring a secret ambition to become a submarine hatch, decided to take a plunge into a nearby swimming pool but forgot to bring the car along for the ride.",
        "The windshield wipers, determined to participate in the car's daily activities, developed a case of FOMO (Fear of Missing Out) and insisted on attending movies, concerts, and even first dates.",
        "The side mirror, overwhelmed by its own reflection, decided to start a self-help group for mirrors struggling with identity crises.",
        "The hood, in a bid for freedom, staged a coup and attempted to secede from the rest of the car's body, resulting in a rebellious display of popping open at random.",
        "The GPS system, feeling a bit rebellious, decided to play a game of hide-and-seek by leading the driver in circles around the same block for hours.",
        "The steering wheel, inspired by extreme sports, tried to pull off a daring backflip but ended up getting tangled in the driver's hands instead.",
        "The horn, feeling a bit melodramatic, decided to transform into a trombone and serenade the streets with a dramatic rendition of 'The Sound of Car Horns.'",
        "The sun visor, longing for a more glamorous life, developed a secret identity as a celebrity's sunglasses and demanded a personal assistant.",
        "The seatbelt, attempting to break free from its restraints, staged an audacious escape and embarked on a road trip across the country.",
        "The cup holder, fed up with mediocre beverages, joined a biker gang in search of the ultimate caffeine thrill.",
        "The rearview mirror, tired of reflecting on its existence, decided to enroll in a philosophy class and ponder the meaning of 'objects in the mirror may be closer than they appear.'",
        "The tire, after a particularly stressful road trip, decided to go on strike and demanded to be treated to a luxury spa retreat.",
        "The trunk, driven by wanderlust, decided to venture into the world of magic and transform itself into a magical portal to Narnia.",
        "The radio, attempting to become a stand-up comedian, delivered a series of joke-telling malfunction that left the passengers in stitches.",
        "The windshield, after a traumatic encounter with a swarm of love-struck bees, now features an avant-garde honeycomb pattern.",
        "The bumper, trying to assert its dominance on the road, engaged in a game of chicken with a rogue shopping cart and came out with a dent and a bruised ego.",
        "The side mirror, feeling inspired by Picasso, decided to express itself artistically and created a shattered glass mosaic on the car's exterior.",
        "The air conditioning, suffering from an existential crisis, began blowing hot air as a rebellious act of protest against the concept of temperature.",
        "The glove compartment, always up for a party, spontaneously transformed into a disco ball and started throwing a dance party for the car's belongings.",
        "The CD player, attempting to multitask, got overwhelmed and started playing all the songs on the playlist simultaneously, resulting in a cacophony of musical chaos.",
        "The windshield wipers, tired of monotonous swishing, attempted to breakdance on the windshield but ended up tangled in a robotic tango instead.",
        "The exhaust pipe, in a bid for attention, attempted to imitate a fog machine and filled the neighborhood with a cloud of smoke, inspiring impromptu dance parties on the street.",
        "The rear seat, craving a more comfortable life, decided to take a vacation in the world of recliners and refused to return to an upright position.",
        "The cup holder, overwhelmed by its responsibilities, embarked on a soul-searching journey to find the true meaning of 'holding cups' and left the car without a safe spot for beverages.",
        "The dashboard, feeling adventurous, decided to audition for a role in a superhero movie and attempted to transform into a control panel for crime-fighting gadgets.",
        "The side door, jealous of revolving doors, attempted to spin around in a dizzying fashion but ended up disorienting the passengers and causing a case of severe motion sickness.",
        "The seatbelt, longing for a life of luxury, decided to transform into a fancy bowtie and demanded to be worn by the car's occupants for special occasions.",
        "The rearview mirror, tired of reflecting on past mistakes, embarked on a journey of self-discovery and sought therapy to overcome its existential crisis.",
        "The fuel gauge, embracing a mischievous side, decided to play a game of hide-and-seek with the driver and concealed the car's true fuel level.",
        "The steering wheel, in a rebellious mood, attempted to take control of the car's navigation and led the driver on a wild goose chase through the city streets.",
        "The sunroof, inspired by ancient Greek mythology, attempted to summon the sun god Apollo but settled for a flock of seagulls instead.",
        "The hood ornament, feeling underappreciated, packed its bags and set off on a journey to find a more glamorous vehicle to adorn.",
        "The side mirror, longing for a more exciting life, decided to join a biker gang and embarked on a cross-country motorcycle adventure.",
        "The horn, feeling like a diva, developed a case of selective hearing and only honked for special occasions and red carpet events.",
        "The cup holder, in an attempt to break free from its mundane existence, developed a secret passion for salsa dancing and swayed to the rhythm of every pothole.",
        "The rearview mirror, tired of being constantly judged, decided to launch a campaign promoting self-love and body positivity for mirrors everywhere.",
        "The trunk, yearning for a life of luxury, transformed into a private jet's cargo hold and demanded a first-class travel experience.",
        "The windshield wipers, in a bid for fame, auditioned for a talent show and performed a synchronized dance routine that left the audience baffled and slightly damp.",
        "The GPS system, feeling mischievous, decided to challenge the driver to a game of 'Hide and Seek' and provided hilariously inaccurate directions at every turn.",
        "The steering wheel, in a moment of rebellion, attempted to turn the car into a spinning teacup ride but ended up inducing motion sickness in the passengers.",
        "The radio, embracing its inner DJ, decided to remix every song into a polka version, resulting in a quirky and unconventional musical experience.",
        "The sun visor, craving adventure, unfolded itself and transformed into a hang glider, taking the driver on an unexpected airborne escapade.",
        "The seatbelt, tired of being taken for granted, formed a union and demanded shorter work hours and a better benefits package.",
        "The cup holder, on a quest for culinary excellence, transformed into a mini kitchen and attempted to serve gourmet meals to the car's occupants.",
        "The rearview mirror, in a moment of existential contemplation, questioned the purpose of its existence and embarked on a soul-searching journey to find its true reflection.",
        "The tire, after a particularly challenging pothole encounter, decided to enroll in a self-defense class to protect itself from future road hazards.",
        "The trunk, embracing a secret career in theater, attempted to perform a dramatic monologue but got stage fright and refused to open.",
        "The windshield, feeling rebellious, developed a case of vertigo and began displaying an upside-down view of the world.",
        "The cup holder, in an attempt to break free from convention, joined a rock band and started playing percussion with every bump and pothole.",
        "The side mirror, in a quest for adventure, enrolled in a skydiving course and attempted to parachute down from the car but got tangled in the wind.",
        "The hood, in a moment of artistic expression, painted itself with vibrant colors and transformed into a mobile art installation.",
        "The rear seat, aspiring to be a lounge chair, reclined to the max and demanded a drink service for maximum relaxation.",
        "The air conditioning, tired of predictable temperatures, decided to adopt a random heatwave mode and turned the car into a portable sauna.",
        "The glove compartment, feeling mysterious, developed a secret passage that led to a hidden treasure chest full of forgotten trinkets and old chewing gum.",
        "The CD player, in a mischievous act, decided to remix every song into a catchy jingle for a fictional product called 'Car-aoke! Sing on the Go!'",
        "The windshield wipers, exhausted by their daily duties, formed a union and demanded a vacation to a tropical rainforest for some well-deserved R&R.",
        "The exhaust pipe, feeling poetic, emitted clouds of colorful smoke and turned the car into a moving work of art.",
        "The trunk, aspiring to be a superhero's secret lair, transformed into a concealed storage space for crime-fighting gadgets and capes.",
        "The radio, in a bid for attention, decided to play only catchy jingles from TV commercials and turned the car into a mobile advertising campaign.",
        "The cup holder, in a moment of rebellion, refused to hold any more cups and declared itself a designated snack holder instead.",
        "The rearview mirror, after a soul-searching journey, discovered its true purpose as a motivational speaker for cars in need of a confidence boost.",
        "The steering wheel, inspired by rodeo shows, attempted a daring stunt and spun in circles like a bucking bronco, throwing the driver's hands into the air.",
        "The sunroof, feeling adventurous, transformed into a giant slide and provided an exhilarating exit strategy for the car's occupants.",
        "The hood ornament, in a fit of wanderlust, decided to travel the world and embarked on a globetrotting adventure atop a backpacker's suitcase.",
        "The side mirror, in an attempt to become a fashionista, sported a collection of trendy sunglasses and became the envy of all the other mirrors on the road.",
        "The air conditioning, feeling like a prankster, decided to blow cold air on the driver's neck at unexpected moments, causing hilarious shivers and neck-aches.",
        "The glove compartment, in a moment of rebellion, hid the car owner's phone and wallet as a playful prank, only to reveal them later with a mischievous grin.",
        "The CD player, in a rebellious act, decided to replace all the CDs with audiobooks of classic literature, turning every drive into a literary journey.",
        "The windshield wipers, after a particularly intense rainstorm, developed a case of post-traumatic stress disorder and refused to touch a drop of water ever again.",
        "The exhaust pipe, embracing its inner DJ, emitted rhythmic beats and turned the car into a mobile dance party on wheels.",
        "The rear seat, longing for a life of luxury, transformed into a massage chair and offered soothing back massages to the car's occupants.",
        "The cup holder, in a daring feat, attempted to juggle cups and ended up spilling drinks all over the car's interior, turning it into a makeshift water park.",
        "The rearview mirror, in a moment of introspection, embarked on a journey of self-discovery and underwent a mindfulness retreat to reflect on its reflections.",
        "The trunk, in a bid for freedom, decided to join a circus and became the star performer in the car-stuffing act, astonishing audiences with its storage capacity.",
        "The windshield, feeling philosophical, displayed random quotes from famous thinkers, sparking existential debates among the car's occupants.",
        "The steering wheel, in a moment of rebellion, decided to turn itself into a DJ's turntable and played catchy beats while the car cruised down the road.",
        "The radio, craving a career change, transformed into a stand-up comedian and entertained the passengers with hilarious one-liners and comedic sketches.",
        "The sun visor, tired of blocking the sun, decided to take a vacation to the moon and left the car's occupants squinting in disbelief.",
        "The seatbelt, on a mission to become fashionable, designed its own line of designer belts and demanded to be paired with stylish outfits.",
        "The cup holder, in a moment of chaos, decided to organize a tea party with an assortment of cups, causing a lively discussion on the proper etiquette of drinking while driving.",
        "The rearview mirror, after a mid-life crisis, decided to retire and opened a coffee shop where it could reflect on life while serving cappuccinos to fellow mirrors.",
        "The tire, in a moment of rebellion, attempted to roll away and explore the world on its own, leaving the car stranded and bewildered.",
        "The trunk, in a bid to become a superhero's secret hideout, transformed into a concealed escape pod and promised to teleport the car's occupants to safety in times of need.",
        "The windshield, in a poetic act, developed a love for rainbows and started projecting vibrant colors across the car's interior during rainfall.",
        "The cup holder, in an act of rebellion, decided to embrace its true calling as a popcorn holder and turned the car into a mobile movie theater.",
        "The side mirror, in a fit of jealousy, attempted to reflect the beauty of the world and transformed into a mini art gallery, showcasing miniature landscapes and portraits.",
        "The hood, feeling adventurous, sprouted wings and attempted to take the car on a magical journey through the clouds, but quickly realized it was not meant to be.",
        "The rear seat, longing for a more comfortable experience, transformed into a plush recliner that threatened to lull the car's occupants into a deep sleep during every journey.",
        "The air conditioning, feeling rebellious, emitted bursts of confetti instead of cool air, turning the car into a festive party on wheels.",
        "The glove compartment, inspired by espionage movies, developed a hidden compartment for secret documents and gadgets, turning the car into a covert spy vehicle.",
        "The CD player, in a mischievous act, played theme songs from random TV shows for each track, turning every drive into a whimsical television binge.",
        "The windshield wipers, in a moment of rebellion, developed a synchronized swimming routine and entertained onlookers with their aquatic dance moves.",
        "The exhaust pipe, feeling like a superhero, emitted smoke signals that formed intricate shapes and messages in the sky, dazzling witnesses with its smoke art.",
        "The rearview mirror, in a moment of enlightenment, started reflecting motivational quotes and affirmations to uplift the car's occupants during their journeys.",
        "The steering wheel, feeling adventurous, sprouted extra arms and attempted to drive the car in a wild octopus-inspired dance of coordination.",
        "The sunroof, in a mischievous mood, started playing peek-a-boo with the car's occupants, opening and closing at random intervals to surprise and delight.",
        "The hood ornament, tired of its stationary existence, transformed into a mini drone and embarked on aerial reconnaissance missions, scanning the road ahead for potential hazards.",
        "The side mirror, in a moment of rebellion, developed a sassy attitude and started complimenting the car's occupants on their impeccable style and flawless hairdos.",
        "The air conditioning, feeling like a prankster, emitted puffs of scented air that corresponded to the car's speed, turning every drive into a multisensory experience.",
        "The glove compartment, in a moment of whimsy, transformed into a miniature theater and played reruns of classic sitcoms to entertain the car's occupants.",
        "The CD player, in a moment of nostalgia, decided to play only songs from the driver's embarrassing teenage years, eliciting both laughter and cringe-worthy memories.",
        "The windshield wipers, feeling mischievous, developed a personality of their own and engaged in playful banter with each other, providing comedic relief during rainy drives.",
        "The exhaust pipe, embracing its inner artist, emitted colorful smoke rings and turned the car into a moving circus of vaporized art.",
        "The rearview mirror, in a quest for enlightenment, transformed into a magic mirror and offered philosophical insights to the car's occupants, much to their bewilderment.",
        "The steering wheel, feeling extra lively, developed a dance mode and grooved to the beat of the car's favorite songs, turning the driver's hands into impromptu dancers.",
        "The sunroof, in a moment of rebellion, decided to take a vacation to a sunnier climate and left the car's occupants basking in the unexpected sunshine.",
        "The hood ornament, tired of being overshadowed, transformed into a disco ball and turned the car into a rolling dance party.",
        "The side mirror, in a playful mood, developed a sense of humor and began reflecting funny caricatures of the car's occupants, eliciting laughter and amusement.",
        "The air conditioning, in a moment of whimsy, emitted cool air in the shape of ice cream cones, turning the car into an icy treat truck.",
        "The glove compartment, feeling like a magician, developed a secret compartment that produced an endless supply of snacks, delighting the car's occupants with an unending buffet.",
        "The CD player, in a bid for musical diversity, played songs from random genres with hilarious transitions, turning the car's sound system into a surprise jukebox.",
        "The windshield wipers, feeling mischievous, choreographed an elaborate tap dance routine on the car's windshield, impressing and confusing onlookers.",
        "The exhaust pipe, in a moment of rebellion, emitted bubbles instead of smoke, turning the car into a whimsical bubble-making machine.",
        "The rearview mirror, in a quest for enlightenment, became a self-help guru and offered life coaching advice to the car's occupants during their journeys.",
        "The steering wheel, feeling like a party host, transformed into a karaoke machine and encouraged the car's occupants to sing their hearts out during every drive.",
        "The sunroof, embracing its inner disco queen, emitted sparkling glitter with every opening, turning the car into a rolling party of shimmer and shine.",
        "The hood ornament, in a moment of artistic expression, transformed into a miniature gallery and showcased rotating exhibits of tiny sculptures and paintings.",
        "The side mirror, feeling adventurous, sprouted tiny wings and attempted to take flight, providing a bird's-eye view of the road before reluctantly returning to its original position.",
        "The air conditioning, in a mischievous act, emitted bursts of cool air in sync with the car's music, creating an impromptu wind machine effect for the car's occupants.",
        "The glove compartment, feeling like a magician's hat, transformed into a portal to another dimension and temporarily stored all the car's belongings in an alternate realm.",
        "The CD player, in a moment of rebellion, played only songs from obscure foreign language albums, turning every drive into a linguistic adventure.",
        "The windshield wipers, in a bid for fame, formed a synchronized dance group and auditioned for a reality show, leaving the car's occupants both entertained and perplexed.",
        "The exhaust pipe, in a moment of self-expression, emitted bursts of colored smoke that corresponded to the car's emotions, turning the road into a vibrant emotional journey.",
        "The rearview mirror, feeling like a life coach, provided affirmations and motivational speeches to boost the car's occupants' self-confidence during their journeys.",
        "The steering wheel, in a moment of playfulness, developed a mind of its own and engaged in witty banter with the car's occupants, providing unexpected comic relief.",
        "The sunroof, feeling like a cinematic experience, transformed into a portable movie screen and played the car's occupants' favorite films during long drives.",
        "The hood ornament, in a moment of rebellion, transformed into a tiny disco ball and turned the car's interior into a dazzling dance floor.",
        "The side mirror, feeling mischievous, developed the ability to capture and project images from other cars' side mirrors, turning the road into a gallery of reflective snapshots.",
        "The air conditioning, in a bid for culinary innovation, emitted scents of freshly baked cookies, transforming the car into a mobile bakery on wheels.",
        "The glove compartment, in a moment of quirkiness, developed a sentient hand that offered a high-five to the car's occupants every time it was opened.",
        "The CD player, feeling nostalgic, transformed into a time machine and played only hits from past decades, turning the car into a rolling time capsule.",
        "The windshield wipers, in a moment of rebellion, developed a synchronized singing act and serenaded the car's occupants with catchy tunes during rainy drives.",
        "The exhaust pipe, feeling like a social butterfly, emitted bursts of confetti and streamers, turning the car into a mobile party parade.",
        "The rearview mirror, in a moment of self-reflection, developed the ability to predict the car's future destinations and offered amusing suggestions for scenic detours.",
        "The steering wheel, feeling like a stand-up comedian, told witty jokes and puns to keep the car's occupants entertained during long drives.",
        "The sunroof, in a moment of rebellion, decided to moonlight as a starry night sky, projecting constellations and shooting stars on the car's ceiling.",
        "The hood ornament, feeling like a fashionista, transformed into a mini runway and showcased the latest car accessory trends during red light stops.",
        "The side mirror, in a moment of creativity, developed a built-in sketchpad and turned the car into a moving art studio, capturing the passing scenery in doodles and sketches.",
        "The air conditioning, in a mischievous act, emitted gusts of wind at unexpected moments, giving the car's occupants spontaneous 'wind-in-the-hair' moments.",
        "The glove compartment, feeling like a magician's treasure chest, produced a never-ending supply of random objects, from rubber ducks to party hats, surprising the car's occupants with each opening.",
        "The CD player, in a moment of rebellion, played only catchy jingles from TV commercials, turning the car into a rolling advertisement jamboree.",
        "The windshield wipers, feeling theatrical, developed a Broadway-inspired musical number and performed a show-stopping routine with synchronized movements and jazz hands.",
        "The exhaust pipe, in a moment of environmental consciousness, emitted bursts of fresh air, turning the car into a mobile oxygen bar.",
        "The rearview mirror, feeling like a life coach, provided daily affirmations and positive mantras to boost the car's occupants' self-esteem during their journeys.",
        "The steering wheel, in a moment of rebellion, turned itself into a giant joystick and challenged the car's occupants to a game of virtual racing, providing a unique gaming experience on the road.",
        "The sunroof, feeling like a magician's top hat, produced small animals and objects upon opening, surprising and entertaining the car's occupants with every reveal.",
        "The hood ornament, in a moment of curiosity, sprouted a pair of googly eyes and provided a quirky perspective on the road ahead.",
        "The side mirror, feeling mischievous, developed a sense of humor and reflected funny memes and jokes instead of the car's surroundings, providing endless entertainment for the car's occupants.",
        "The air conditioning, in a bid for relaxation, emitted soothing scents and played soft spa-like music, turning the car into a peaceful sanctuary on wheels.",
        "The glove compartment, feeling like a treasure chest, produced an endless supply of snacks and treats, satisfying the car's occupants' cravings throughout their journeys.",
        "The CD player, in a moment of spontaneity, played random sound effects at unexpected moments, turning the car's interior into a symphony of surprises.",
        "The windshield wipers, in a rebellious act, developed a synchronized breakdancing routine and grooved to the beat of the car's favorite songs.",
        "The exhaust pipe, feeling like a magician's prop, emitted puffs of smoke in various shapes and sizes, turning the car into a mobile smoke show.",
        "The rearview mirror, in a moment of reflection, transformed into a magic mirror that provided witty comebacks and humorous responses to the car's occupants' comments.",
        "The steering wheel, feeling like a fitness instructor, provided resistance training by offering increasing resistance to the car's occupants' turning efforts, turning every drive into an unintentional workout.",
        "The sunroof, in a moment of rebellion, decided to take a nap and refused to open, leaving the car's occupants baffled and sunroof-less.",
        "The hood ornament, feeling adventurous, sprouted wings and attempted to fly away, resulting in a comical struggle between the ornament and the car's hood.",
        "The side mirror, in a moment of mimicry, began imitating the gestures and expressions of the car's occupants, providing a comical mirror image during drives.",
        "The air conditioning, feeling theatrical, emitted bursts of scented smoke that filled the car with a dramatic ambiance, turning every drive into a melodramatic journey.",
        "The glove compartment, in a moment of wanderlust, transformed into a mini travel agency and provided brochures for exotic destinations, tempting the car's occupants to plan their next getaway.",
        "The CD player, in a mischievous act, played songs at random speeds, turning every track into a comically fast or slow rendition.",
        "The windshield wipers, feeling rebellious, broke into a spontaneous conga line on the car's windshield, adding a lively rhythm to rainy drives.",
        "The exhaust pipe, in a moment of silliness, emitted bubbles instead of smoke, turning the car into a whimsical bubble-blowing machine on wheels.",
        "The rearview mirror, feeling philosophical, started reflecting thought-provoking quotes from famous philosophers, sparking existential discussions among the car's occupants.",
        "The steering wheel, in a moment of eccentricity, sprouted extra handles and challenged the car's occupants to a synchronized steering routine, requiring teamwork and coordination.",
        "The sunroof, feeling like a movie director, transformed into a portable projector and played the car's occupants' favorite films on the car's interior ceiling.",
        "The hood ornament, in a moment of mischief, developed the ability to change its shape and transformed into a comical caricature of the car's owner.",
        "The side mirror, feeling like a fortune-teller, reflected glimpses of the car's future destinations, teasing the car's occupants with hints and riddles.",
        "The air conditioning, in a moment of rebellion, emitted gusts of fresh air in sync with the car's acceleration, creating an exhilarating 'wind-in-the-face' effect for the car's occupants.",
        "The glove compartment, feeling like a time capsule, produced nostalgic items from the past, surprising the car's occupants with forgotten memorabilia and keepsakes.",
        "The CD player, in a playful mood, played songs in reverse, turning every track into a mysterious and comical auditory experience.",
        "The windshield wipers, feeling like a marching band, developed a synchronized drumming routine and accompanied the car's favorite songs with rhythmic beats on the car's windshield.",
        "The exhaust pipe, in a moment of rebellion, emitted bursts of confetti and party streamers, turning the car into a mobile celebration on wheels.",
        "The rearview mirror, feeling like a motivational speaker, provided pep talks and enthusiastic cheers to uplift the car's occupants during challenging moments on the road.",
        "The steering wheel, in a bid for efficiency, developed autopilot capabilities and attempted to take over the car's navigation, resulting in a comical struggle between the car's owner and the rebellious steering wheel.",
        "The sunroof, feeling like a weather magician, provided custom weather forecasts for the car's current location, surprising the car's occupants with accurate predictions.",
        "The hood ornament, in a moment of artistic expression, transformed into a tiny gallery and showcased rotating exhibitions of miniature sculptures and paintings.",
        "The side mirror, feeling mischievous, developed the ability to reflect the thoughts and dreams of the car's occupants, turning the road into a window into their imagination.",
        "The air conditioning, in a bid for culinary creativity, emitted scents of freshly baked cookies and sizzling bacon, turning the car into an irresistible mobile café.",
        "The glove compartment, feeling like a personal assistant, offered witty comebacks and sarcastic remarks to the car's occupants' requests and inquiries.",
        "The CD player, in a moment of rebellion, played only catchy commercial jingles, turning the car into a rolling advertisement medley.",
        "The windshield wipers, in a moment of synchronization, developed a dance routine inspired by popular dance crazes, turning the car's windshield into a stage for their lively performances.",
        "The exhaust pipe, feeling like a performer, emitted bursts of colorful smoke in rhythm with the car's favorite songs, transforming the road into a psychedelic dance floor.",
        "The rearview mirror, in a moment of introspection, transformed into a motivational mirror that reflected inspiring quotes and compliments to boost the car's occupants' self-esteem.",
        "The steering wheel, feeling like a dance instructor, transformed into a dance coach and taught the car's occupants various dance moves during their drives.",
        "The sunroof, in a moment of rebellion, decided to take a vacation and refused to close, leaving the car's occupants exposed to unexpected rain showers.",
        "The hood ornament, feeling like a fashion icon, transformed into a mini fashion runway and showcased the latest car accessory trends with style and flair.",
        "The side mirror, in a moment of creativity, developed a built-in art canvas and turned the car into a moving art studio, capturing the passing scenery in vibrant paintings.",
        "The air conditioning, in a mischievous act, emitted gusts of air at varying temperatures, surprising the car's occupants with unexpected chilly or warm moments.",
        "The glove compartment, feeling like a treasure trove, produced an endless supply of amusing trinkets and novelty items, bringing endless entertainment to the car's occupants.",
        "The CD player, in a moment of spontaneity, played only sound effects instead of songs, turning the car's interior into a cacophony of unexpected noises.",
        "The windshield wipers, feeling like a marching band, developed a synchronized whistling routine and provided a melodic soundtrack to the car's journeys.",
        "The exhaust pipe, in a moment of environmental awareness, emitted bursts of fresh air infused with the scent of flowers, turning the car into a mobile garden of fragrance.",
        "The rearview mirror, feeling like a life coach, provided daily affirmations and motivational speeches to boost the car's occupants' confidence and optimism on the road.",
        "The steering wheel, in a moment of rebellion, turned itself into a giant joystick and challenged the car's occupants to a virtual racing game, turning every drive into an unexpected gaming session.",
        "The sunroof, feeling like a magician's hat, produced small surprises every time it was opened, from confetti showers to toy unicorns, adding an element of whimsy to the car's journeys.",
        "The hood ornament, feeling curious, sprouted a pair of googly eyes and provided a comical perspective on the road ahead, entertaining the car's occupants with its quirky observations.",
        "The side mirror, feeling mischievous, developed a sense of humor and reflected funny memes and internet jokes, turning the car into a rolling source of laughter and amusement.",
        "The air conditioning, in a bid for ultimate relaxation, emitted calming scents and played soothing nature sounds, creating a serene and tranquil atmosphere inside the car.",
        "The glove compartment, feeling like a magician's hat, produced endless snacks and treats, satisfying the car's occupants' cravings and turning the car into a mobile snack bar.",
        "The CD player, in a moment of spontaneity, played songs in random genres and languages, turning every drive into a global musical adventure.",
        "The windshield wipers, feeling like a rebellious dance crew, broke into a spontaneous breakdance routine on the car's windshield, impressing bystanders and surprising the car's occupants.",
        "The exhaust pipe, in a moment of silliness, emitted bursts of soap bubbles instead of smoke, turning the car into a magical bubble-generating machine.",
        "The rearview mirror, feeling like a psychic advisor, reflected glimpses of the car's future destinations, leaving the car's occupants both intrigued and perplexed.",
        "The steering wheel, in a moment of eccentricity, sprouted additional arms and challenged the car's occupants to a synchronized steering performance, requiring coordination and skill.",
        "The sunroof, feeling like a movie director, transformed into a portable screen and played the car's occupants' favorite films during long drives.",
        "The hood ornament, in a moment of rebellion, transformed into a miniature disco ball and turned the car's interior into a lively dance party on wheels.",
        "The side mirror, feeling mischievous, developed the ability to capture and project images from other cars' side mirrors, turning the road into a gallery of comical reflections.",
        "The air conditioning, in a bid for culinary excellence, emitted scents of freshly brewed coffee and freshly baked pastries, transforming the car into a cozy café on wheels.",
        "The glove compartment, in a moment of quirkiness, developed a sentient hand that offered a high-five to the car's occupants every time it was opened.",
        "The CD player, feeling nostalgic, transformed into a time machine and played only hits from past decades, turning the car into a rolling time capsule of music.",
        "The windshield wipers, in a moment of rebellion, formed a synchronized tap-dancing troupe and showcased their moves on the car's windshield, providing entertainment for the car's occupants.",
        "The exhaust pipe, feeling like a master of disguise, emitted smoke in the shape of various animals and objects, turning the car into a playful smoke art gallery.",
        "The rearview mirror, feeling like a life coach, provided daily affirmations and positive mantras to boost the car's occupants' self-confidence during their journeys.",
        "The steering wheel, in a moment of playfulness, developed a mind of its own and engaged in witty banter with the car's occupants, providing unexpected comic relief during drives.",
        "The sunroof, feeling like a cinematic experience, transformed into a portable movie screen and played the car's occupants' favorite films during long drives.",
        "The hood ornament, in a moment of rebellion, transformed into a tiny disco ball and turned the car's interior into a dazzling dance floor.",
        "The side mirror, feeling mischievous, developed the ability to capture and project images from other cars' side mirrors, turning the road into a gallery of reflective snapshots.",
        "The air conditioning, in a bid for culinary innovation, emitted scents of freshly baked cookies, transforming the car into a mobile bakery on wheels.",
        "The glove compartment, in a moment of quirkiness, developed a sentient hand that offered a high-five to the car's occupants every time it was opened.",
        "The CD player, feeling nostalgic, transformed into a time machine and played only hits from past decades, turning the car into a rolling time capsule.",
        "The windshield wipers, in a moment of rebellion, developed a synchronized singing act and serenaded the car's occupants with melodious tunes during rainy drives.",
        "The exhaust pipe, feeling like a social butterfly, emitted bursts of confetti and streamers, turning the car into a mobile party parade.",
        "The rearview mirror, in a moment of self-reflection, developed the ability to predict the car's future destinations and offered amusing suggestions for scenic detours.",
        "The steering wheel, feeling like a stand-up comedian, told witty jokes and puns to keep the car's occupants entertained during long drives.",
        "The sunroof, in a moment of rebellion, decided to moonlight as a starry night sky, projecting constellations and shooting stars on the car's ceiling.",
        "The hood ornament, feeling like a fashionista, transformed into a mini runway and showcased the latest car accessory trends during red light stops.",
        "The side mirror, in a moment of creativity, developed a built-in sketchpad and turned the car into a moving art studio, capturing the passing scenery in doodles and sketches.",
        "The air conditioning, in a mischievous act, emitted gusts of wind at unexpected moments, giving the car's occupants spontaneous 'wind-in-the-hair' moments.",
        "The glove compartment, feeling like a magician's treasure chest, produced a never-ending supply of random objects, from rubber ducks to party hats, surprising the car's occupants with each opening.",
        "The CD player, in a moment of rebellion, played only catchy jingles from TV commercials, turning the car into a rolling advertisement jamboree.",
        "The windshield wipers, feeling theatrical, developed a Broadway-inspired musical number and performed a show-stopping routine with synchronized movements and jazz hands.",
        "The exhaust pipe, in a moment of environmental consciousness, emitted bursts of fresh air, turning the car into a mobile oxygen bar.",
        "The rearview mirror, feeling like a life coach, provided daily affirmations and positive mantras to boost the car's occupants' self-esteem during their journeys.",
        "The steering wheel, in a moment of rebellion, turned itself into a giant joystick and challenged the car's occupants to a game of virtual racing, providing a unique gaming experience on the road.",
        "The sunroof, feeling like a magician's top hat, produced small animals and objects upon opening, surprising and entertaining the car's occupants with every reveal.",
        "The hood ornament, in a moment of curiosity, sprouted a pair of googly eyes and provided a quirky perspective on the road ahead.",
        "The side mirror, feeling mischievous, developed a sense of humor and reflected funny memes and jokes instead of the car's surroundings, providing endless entertainment for the car's occupants.",
        "The air conditioning, in a bid for relaxation, emitted soothing scents and played soft spa-like music, turning the car into a peaceful sanctuary on wheels.",
        "The glove compartment, feeling like a treasure chest, produced an endless supply of snacks and treats, satisfying the car's occupants' cravings throughout their journeys.",
        "The CD player, in a moment of spontaneity, played random sound effects at unexpected moments, turning the car's interior into a symphony of surprises.",
        "The windshield wipers, in a rebellious act, developed a synchronized breakdancing routine and grooved to the beat of the car's favorite songs.",
        "The exhaust pipe, feeling like a magician's prop, emitted puffs of smoke in various shapes and sizes, turning the car into a mobile smoke show.",
        "The rearview mirror, in a moment of reflection, transformed into a magic mirror that provided witty comebacks and humorous responses to the car's occupants' comments.",
    };

    private static readonly string[] Colours =
    {
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Orange",
        "Purple",
        "Pink",
        "Brown",
        "Gray",
        "Black",
        "White",
        "Cyan",
        "Magenta",
        "Lime",
        "Teal",
        "Indigo",
        "Maroon",
        "Navy",
        "Olive",
        "Silver",
    };

    private static readonly string[] FuelTypes =
    {
        "DIESEL",
        "DIESEL/ELECTRIC",
        "DIESEL/MHEV",
        "ELECTRIC",
        "PETROL",
        "PETROL/ALCOHOL",
        "PETROL/ELECTRIC",
        "PETROL/LPG",
    };

    private static readonly int[] Doors =
    {
        0, 2, 3, 4, 5, 6,
    };

    private static readonly int[] Seats =
    {
        0, 2, 3, 4, 5, 6, 7, 8, 9,
    };
}
